site_name: jsoncf
repo_url: https://github.com/idlewith/jsoncf
site_url: https://idlewith.github.io/jsoncf
site_description: prettify json string from clipboard
site_author: idlewith


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - Modules: modules.md

copyright: Maintained by idlewith.
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true