name: pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.3.1 mkdocs-material==8.4.2 mkdocs-material-extensions==1.0.3 mkdocstrings==0.19.0 mkdocstrings-python==0.7.1
      - run: mkdocs gh-deploy --force